### ISSUE TITLE
http Request 

### ISSUE THREAD

**Issue by Jumbo125** [csabag/BoostedGcodeCuraPlugin#1]
sorry work.

**Comment by csabag** [comment]
Hi Jumbo125,

I saw you edited your comment. Does this mean it works for you?

Csaba

**Comment by Jumbo125** [comment]
Hello
Thank you for your answer. I didn't use your script. I tried to wrote a script, which use a request, but it didn't work. So i would ask you, if you can help me. Fortunately it works now. It was my fail. I thought post process script def execute run on "press slicing" and i didn't get any message. Yesterday i press after slice on "save" and suddenly the script runs. Now i know, tat the fail was only to forgot "press save" after "press slicing"

Thank you

**Comment by csabag** [comment]
Glad that it worked for you.
